highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://adejuyigbe.com"
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
sass:
  style: compressed
katex:
  js_path: "assets"
  rendering_options:
    throw_error: false
    error_color: "#cc0000"
